Add OpenPGP message signer
swiftmailer/swiftmailer pull request #1136
Opened 2018-10-05 16:06 UTC by digilist

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc update?   | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #737 
| License       | MIT

I added a OpenPGP message signer that is able to sign and encrypt messages. My code is based on the one that @postme provided in #737, but I cleaned it up and added tests.

Enigmail/Thunderbird was able to decrypt and verify the generated messages. However, I am not totally sure if everything is correct.

One thing I am especially not sure about is the micalg header parameter. The parameter must define the used hashing algorithm, but PHP does not allow to define the algorithm. Currently the code names SHA256 as micalg (which I just adopted from @postme's code), so I am not sure about this.

In my tests with Enigmail the micalg value didn't matter at all. I could remove it and Enigmail still said my signature was good. However, according to [RFC 3156](https://tools.ietf.org/html/rfc3156) the micalg parameter is required, so I do not think it should stay this way.

> The "micalg" parameter for the "application/pgp-signature" protocol MUST contain exactly one hash-symbol of the format "pgp-<hash-identifier>", where <hash-identifier> identifies the Message Integrity Check (MIC) algorithm used to generate the signature.

2018-10-17 10:50 UTC, Rotzbua commented
Interesting pr. But test fails. Seems incomplete.

> Swift_IoException: Unable to find an active key to encrypt for test@example.org, try importing keys first

2018-10-17 11:29 UTC, digilist commented
Yes, that's true and unfortunately I do not know why. Locally those tests are running and I think it might be a different PGP version, but I do not know how to confirm that. I was hoping, someone else got an idea.

I am using this signer in another project in production and it's working. It's unit tested there as well and locally all tests are running and the signing works, but we experienced the same failing test behavior behavior with Scrutinizer.

2018-10-17 22:40 UTC, Rotzbua requested changes
5 minute review, maybe env vars are not set correctly and the keys are not found

2018-10-17 22:40 UTC, Rotzbua commented on lib/classes/Swift/Signers/OpenPGPSigner.php
> +     * @return bool|mixed
should be only bool

2018-10-17 22:40 UTC, Rotzbua commented on lib/classes/Swift/Signers/OpenPGPSigner.php
> +            $plaintextBody = sprintf("%s\r\n%s", $message->getHeaders()->get('Content-Type')->toString(), $plaintextBody);
single quote

2018-10-17 22:40 UTC, Rotzbua commented on lib/classes/Swift/Signers/OpenPGPSigner.php
> +            putenv("GNUPGHOME=" . escapeshellcmd($gnupgHome));
single quote and success should be checked

2018-10-17 22:40 UTC, Rotzbua commented on tests/unit/Swift/Signers/OpenPGPSignerTest.php
> +        putenv("GNUPGHOME=" . escapeshellcmd(self::GNUPG_HOME));
check success

2021-11-15 15:05 UTC, fabpot commented
Thanks for the PR. As announced some time ago, Swiftmailer is not maintained anymore.

[Symfony Mailer](https://symfony.com/doc/current/mailer.html) is the next evolution of Swiftmailer.
It provides the same features with support for modern PHP code and support for third-party providers.

2021-11-15 15:05 UTC, closed without merging